return {
   samples = {
      overlapping = {
         {N = 2, name = "Chess", periodic = true},
         {N = 2, height = 47, name = "Chess", periodic = true, screenshots = "1", width = 47},
         {N = 3, ground = -1, name = "Skyline", periodic = true, symmetry = 2},
         {N = 3, ground = -4, name = "Flowers", periodic = true, symmetry = 2},
         {N = 3, name = "Hogs", periodic = true},
         {N = 2, name = "Hogs", periodic = true},
         {N = 3, name = "Knot", periodic = true},
         {N = 3, name = "LessRooms", periodic = true},
         {N = 3, name = "Mountains", periodic = true, symmetry = 2},
         {N = 3, name = "Office", periodic = true},
         {N = 3, name = "Paths", periodic = true},
         {N = 2, ground = -1, name = "Platformer", periodic = true, symmetry = 2},
         {N = 3, ground = -1, name = "Platformer", periodic = true, symmetry = 2},
         {N = 2, name = "RedMaze"},
         {N = 3, name = "Rooms", periodic = true, screenshots = "3"},
         {N = 3, name = "Rule126", periodic = false, periodicInput = false, symmetry = 2},
         {N = 3, name = "SimpleKnot", periodic = true},
         {N = 2, name = "SimpleMaze"},
         {N = 3, name = "SimpleWall", periodic = true, symmetry = 2},
         {N = 3, name = "SimpleWall", periodic = true},
         {N = 2, name = "SimpleWall", periodic = true, symmetry = 2},
         {N = 2, name = "SimpleWall", periodic = true},
         {N = 3, name = "TrickKnot", periodic = true},
         {N = 3, name = "Village", periodic = true, symmetry = 2},
         {N = 3, name = "Water", periodic = true, symmetry = 1},
         {N = 3, height = 80, name = "Cat", periodic = true, symmetry = 2, width = 80},
         {N = 3, name = "Cats", periodic = true, symmetry = 2},
         {N = 3, ground = -1, name = "Skyline2", periodic = true, symmetry = 2},
         {N = 3, name = "Angular", periodic = true},
         {N = 3, height = 80, name = "City", periodic = true, width = 80},
         {N = 3, name = "ColoredCity", periodic = true},
         {N = 3, name = "Dungeon", periodic = true},
         {N = 3, height = 60, name = "Lake", periodic = true, width = 60},
         {N = 3, name = "Link", periodic = true},
         {N = 3, name = "Link2", periodic = true},
         {N = 3, name = "Mazelike", periodic = true},
         {N = 3, name = "Nested", periodic = true},
         {N = 3, name = "MagicOffice", periodic = true},
         {N = 3, name = "Office2", periodic = true},
         {N = 3, height = 80, name = "Qud", periodic = true, width = 80},
         {N = 3, name = "RedDot", periodic = true},
         {N = 2, name = "ScaledMaze", periodic = true},
         {N = 3, name = "Sewers", periodic = true},
         {N = 3, name = "Skew1", periodic = true},
         {N = 3, name = "Skew2", periodic = true},
         {N = 3, name = "SmileCity", periodic = true},
         {N = 3, name = "Spirals", periodic = true},
         {N = 3, name = "Town", periodic = true},
         {N = 3, name = "3Bricks", periodic = true, symmetry = 1},
         {N = 3, limit = "50", name = "Village", periodic = true, symmetry = 2}
      },
      simpletiled = {
         {height = 15, name = "Summer", width = 15},
         {height = 20, name = "Castle", width = 20},
         {height = 34, name = "Circuit", periodic = true, screenshots = "3", subset = "Turnless", width = 34},
         {height = 24, name = "Knots", periodic = true, subset = "Standard", width = 24},
         {height = 24, name = "Knots", periodic = true, subset = "Dense", width = 24},
         {height = 24, name = "Knots", subset = "Crossless", width = 24},
         {height = 24, name = "Knots", subset = "TE", width = 24},
         {height = 24, name = "Knots", subset = "T", width = 24},
         {height = 24, name = "Knots", subset = "CL", width = 24},
         {height = 24, name = "Knots", periodic = true, subset = "CE", width = 24},
         {height = 24, name = "Knots", periodic = true, subset = "C", width = 24},
         {height = 24, name = "Knots", periodic = true, subset = "Fabric", width = 24},
         {height = 24, name = "Knots", periodic = true, subset = "Dense Fabric", width = 24},
         {height = 30, name = "Rooms", width = 30},
         {height = 24, name = "Circles", width = 24},
         {height = 24, name = "Circles", subset = "Large Circles", width = 24},
         {height = 24, name = "Circles", subset = "Large Circles and Solid", width = 24},
         {height = 24, name = "Circles", subset = "No Solid", width = 24},
         {height = 15, limit = "15", name = "Summer", periodic = false, width = 15},
         {height = 5, name = "Knots", periodic = true, subset = "Standard", textOutput = true, width = 5},
         {height = 6, name = "Summer", periodic = false, textOutput = true, width = 6},
         {height = 7, name = "Circuit", periodic = true, subset = "Turnless", textOutput = true, width = 7}
      }
   }
}
